your_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      dbname: analytics
      schema: public
      threads: 1
