olist:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: admin
      password: admin
      port: 5432
      dbname: olist
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10