
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d airflow_meta"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.7.3
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: "${AIRFLOW_SECRET_KEY}"  # Different from Fernet key
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW_FERNET_KEY}"       # Separate Fernet key
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/airflow_meta
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      TZ: UTC
    entrypoint: bash -c "airflow db init && airflow users create \
      --username admin \
      --firstname admin \
      --lastname admin \
      --role Admin \
      --email admin@example.com \
      --password admin"
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    command: webserver
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: "${AIRFLOW_SECRET_KEY}"
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW_FERNET_KEY}"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/airflow_meta
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      TZ: UTC
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt/ecommerce:/opt/airflow/dbt/ecommerce:rw
      - ./airflow/scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - airflow-init

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    command: scheduler
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: "${AIRFLOW_SECRET_KEY}"
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW_FERNET_KEY}"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/airflow_meta
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      TZ: UTC
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt/ecommerce:/opt/airflow/dbt/ecommerce:rw
      - ./airflow/scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

volumes:
  pgdata:
