services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d olist"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.0
    container_name: dbt
    volumes:
      - ./dbt:/opt/airflow/dbt
    working_dir: /opt/airflow/dbt
    environment:
      DBT_PROFILES_DIR: /opt/airflow/dbt
    depends_on:
      postgres:
        condition: service_healthy

  airflow-init:
    image: apache/airflow:2.7.3
    build: ./airflow
    entrypoint: bash -c "airflow db migrate && airflow users create \
      --username admin \
      --firstname admin \
      --lastname admin \
      --role Admin \
      --email admin@example.com \
      --password admin"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/airflow_meta
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: False   # ← unpause at creation
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: False
      AIRFLOW__WEBSERVER__EXPOSE_HOSTNAME: False
      AIRFLOW__WEBSERVER__EXPOSE_STACKTRACE: False

  airflow:
    build: ./airflow
    image: custom-airflow:dbt
    command: [ "standalone" ]
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/airflow_meta
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: False   # ← unpause at creation
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      DATA_DIR: /opt/airflow/data

      DBT_PROFILES_DIR: /opt/airflow/dbt
      DBT_PROJECT_DIR: /opt/airflow/dbt

      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: keyvan.tajbakhsh@gmail.com
      AIRFLOW__SMTP__SMTP_USER: keyvan.tajbakhsh@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: hwln vecu oahx gkkc
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./dbt:/opt/airflow/dbt:z
    user: "50000:0"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  etl-python:
    build:
      context: ./python_scripts
      dockerfile: Dockerfile
    image: etl-python:latest
    container_name: etl-python
    volumes:
      - ./python_scripts:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
